version: "4"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  scylla:
    extends:
      file: docker-compose.base.yml
      service: scylla

  backend:
    build: "./admin-server"
    extends:
      file: docker-compose.base.yml
      service: backend
    depends_on:
      postgres:
        condition: service_healthy
      scylla:
        condition: service_healthy

networks:
  app_network:
    driver: bridge

volumes:
  tmp:
